# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# C:\b\abs_feluzs5bp9\clone\recipe, last modified Wed Jan 31 10:16:08 2024
# ------------------------------------------------

package:
  name: aws-c-io
  version: 0.13.10
source:
  sha256: 4e7caa335ece916c00f4c9896e7413bb6ed52abc77e2c3dda3ffe5bcf3fc8655
  url: https://github.com/awslabs/aws-c-io/archive/v0.13.10.tar.gz
build:
  number: '0'
  run_exports:
    - aws-c-io >=0.13.10,<0.13.11.0a0
  string: h2bbff1b_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - cmake 3.26.4 h693b641_0
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - ninja-base 1.10.2 h6d14046_5
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.5 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.5 hd43e919_0
  host:
    - aws-c-cal 0.5.20 h2bbff1b_0
    - aws-c-common 0.8.5 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - aws-c-cal >=0.5.20,<0.5.21.0a0
    - aws-c-common >=0.8.5,<0.8.6.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - if not exist %LIBRARY_INC%\\aws\\io\\io.h exit 1
    - if not exist %PREFIX%\\Library\\bin\\aws-c-io.dll exit 1
about:
  description: 'This is an event driven framework for implementing application protocols.
    It is built on top of cross-platform

    abstractions that allow you as a developer to think only about the state machine
    and API for your protocols.

    A typical use-case would be to write something like Http on top of asynchronous-io
    with TLS already baked in.

    All of the platform and security concerns are already handled for you.

    '
  dev_url: https://github.com/awslabs/aws-c-io
  doc_url: https://github.com/awslabs/aws-c-io
  home: https://github.com/awslabs/aws-c-io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: This is a module for the AWS SDK for C. It handles all IO and TLS work
    for application protocols.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: fe9cdc31-e719-4d1c-8a41-221b47a85754
  recipe-maintainers:
    - conda-forge/aws-sdk-cpp
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/aws-c-io-feedstock.git
  sha: dc9ad0f3719845b74f9911a25e688d9fdbbf2ad6
